# Generated by Django 4.2.7 on 2023-12-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='tags',
            field=models.ManyToManyField(to='myapp.tag'),
        ),
    ]
